// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryManager.Model;

namespace SalaryManager.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20190127212735_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("SalaryManager.Model.Chief", b =>
                {
                    b.Property<int>("ChiefId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ChiefId");

                    b.ToTable("Chiefs");
                });

            modelBuilder.Entity("SalaryManager.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChiefId");

                    b.Property<int>("EmployeeBaseSalaryRate");

                    b.Property<string>("EmployeeDateOfEmployment");

                    b.Property<string>("EmployeeName");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ChiefId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SalaryManager.Model.EmployeeGroup", b =>
                {
                    b.Property<int>("EmployeeGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChiefId");

                    b.Property<string>("EmployeeGroupName");

                    b.Property<int>("EmployeeId");

                    b.HasKey("EmployeeGroupId");

                    b.HasIndex("ChiefId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeGroups");
                });

            modelBuilder.Entity("SalaryManager.Model.Employee", b =>
                {
                    b.HasOne("SalaryManager.Model.Chief", "Chief")
                        .WithMany("Employees")
                        .HasForeignKey("ChiefId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SalaryManager.Model.EmployeeGroup", b =>
                {
                    b.HasOne("SalaryManager.Model.Chief", "Chief")
                        .WithMany("EmployeeGroups")
                        .HasForeignKey("ChiefId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SalaryManager.Model.Employee", "Employee")
                        .WithMany("EmployeeGroups")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
